### ISSUE TITLE
Consent required: but url returns error invalid response type

### ISSUE THREAD

**Issue by cmosgh** [docusign/eg-01-node-jwt#14]
I am using the example but when accessing the generated url I am getting error `invalid/unaccepted response type` - can't see the message in english my browser shows it in my own language

here is the formated url: `https://account-d.docusign.com/oauth/auth?response_type=code&scope=signature%20impersonation&client_id=42b6cb54-7829-4dcd-affe-d83b0e467fe4&redirect_uri=https://www.docusign.com`

**Comment by LarryKlugerDS** [comment]
Invalid response type means that your integration key is set for Implicit Grant instead of Authorization Code grant.

**Comment by cmosgh** [comment]
Yeah I looked at it and for some reason I've changed it to Implicit Grant.
Thank you @LarryKlugerDS
