### ISSUE TITLE
tokenTimestamp Issue

### ISSUE THREAD

**Issue by dipta007** [docusign/eg-01-node-jwt#6]
In `lib/dsJwtAuth.js` file, why do we have to add the `tokeReplaceMin` on this [line](https://github.com/docusign/eg-01-node-jwt/blob/2eff09a046d94afedc8fca87c65d592de7641f2a/lib/dsJwtAuth.js#L57) . As we are getting the timeStamp of the expiration from the server. And if the current time is later than the expiration time, we have to request for a new one. So why do we have to add `tokeReplaceMin` with it?

I think the line should be this - 

```
let noToken = !DsJwtAuth.accessToken || !tokenExpirationTimestamp
    , now = moment()
    , needToken = noToken || tokenExpirationTimestamp.isBefore(now);
```

**Comment by LarryKlugerDS** [comment]
Thank you for the PR! I've commented on the PR itself.

`tokeReplaceMin` is a buffer time.
