### ISSUE TITLE
ReferenceError: results is not defined

### ISSUE THREAD

**Issue by by12380** [docusign/eg-01-node-jwt#7]
On eg-01-node-jwt/index.js Line 44, `results` is not declared. Add `let` before `results` fixes the problem.

i.e.
`let results = await listEnvelopes.listEnvelopes();`

**Comment by LarryKlugerDS** [comment]
Thank you! We'll get that updated.

**Comment by LarryKlugerDS** [comment]
results is declared on line 40. It's used for the results from both API calls.
